name: Integración continua

on:
  push:
      branches:  [ master ]
      paths: [ 'hangman-api/**' ]
  pull_request:
      branches:  [ master ]
      paths: [ 'hangman-api/**' ]

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        working-directory: ./hangman-api
        run: |
           npm ci
            npm run build
            npm run test
          
