name: Integración continua

on:
  push:
      branches:  [ master ]
  pull_request:
      branches:  [ master ]

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build
        working-directory: ./hangman-api
          run: |
           npm ci
            npm run build
            npm run test
          
