name: Integración continua

on:
  push:
      branches:  [ master ]
  pull_request:
      branches:  [ master ]

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Inspeccionar la máquina
        run:
          ls -alh
          whoami
          pwd
          node -v 
